### ISSUE TITLE
Add <p> to blockquote in The Blessed City

### ISSUE THREAD

**Issue by robinwhittleton** [samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems#1]
The Blessed City blockquote should probably have a `<p>` wrapping the text. This is also opening a can of worms, but I’d remove the `non-fiction` tag from it too.

**Comment by samisiddiqui** [comment]
The <p> tag has been added, but the nonfiction tag stands. It's [Matthew 5:29-30](https://www.biblegateway.com/passage/?search=Matthew+5%3A29-30&version=KJV), and per the semantics manual, we give it the nonfiction tag because it's a real-life quote in a fictional work.
