### ISSUE TITLE
Linebreaks in Faces

### ISSUE THREAD

**Issue by robinwhittleton** [samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems#2]
The `<br>`s in [Faces](https://github.com/samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems/blob/eda8e58f39e812ca7d391ac2e1a472cc6c204a06/src/epub/text/faces.xhtml) don’t match the default styling in SE, but looking at the source I can see why you’ve marked it up like that.

![Example from the original printed source showing line breaks in between each paragraph.](https://user-images.githubusercontent.com/7414/37722793-2878cb22-2d2d-11e8-905d-e92ac6533c44.png)

@acabal, got an opinion on what to do here? We could go with default SE style, leave the line breaks in, or add extra margin to the paragraphs in this particular story?

**Comment by acabal** [comment]
Hmm... I think generally we want to use as few `<br>`s as possible, and only when other kinds of styling don't make sense, like in a multi-line dedication where one sentence is broken into several lines for stylistic effect.

Also `<br>` is a "line break" which implies that a single line is being broken into several (again, like a stylized dedication). Here it looks like we have separate lines with extra margins and we're using `<br>` merely as a substitute for presentational style. A small difference but one worth examining.

Given that, I would remove the `<br>`s and instead add this style to `local.css`: `#faces p + p{ margin-top: 1em; }`

(Sorry I'm late to this issue, Github doesn't seem to notify me when I'm mentioned somewhere.)

**Comment by acabal** [comment]
The other alternative is to use `<hr>` but that would add a divider, and I don't think that's semantically correct anyway, as these are not "thematic breaks" but rather a presentational style choice for this specific piece.

**Comment by samisiddiqui** [comment]
I went with the CSS insert you provided.
