### ISSUE TITLE
Two stories are missing quotes around their titles

### ISSUE THREAD

**Issue by robinwhittleton** [samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems#3]
Both “Defeat“ and “The Perfect World” are quoted in the original scans, but are missing quotes here.

**Comment by samisiddiqui** [comment]
Resolved as of https://github.com/samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems/commit/acf96c1aecf87d5a77c8047dd74742b79a1a1141
