### ISSUE TITLE
Artist needs both a full-name and file-as

### ISSUE THREAD

**Issue by robinwhittleton** [samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems#4]
https://github.com/samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems/blob/eda8e58f39e812ca7d391ac2e1a472cc6c204a06/src/epub/content.opf#L65

This should be split into two entries: a `file-as` with the value `Tissot, James` and a `se:name.person.full-name` with the value `Jacques Joseph Tissot`.

**Comment by samisiddiqui** [comment]
Resolved as of https://github.com/samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems/commit/71562efc4e1feb37a8a56b846c8b6e60dc1505b0
