### ISSUE TITLE
Cover and titlepage differ

### ISSUE THREAD

**Issue by robinwhittleton** [samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems#5]
https://github.com/samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems/blob/eda8e58f39e812ca7d391ac2e1a472cc6c204a06/src/epub/images/cover.svg

https://github.com/samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems/blob/eda8e58f39e812ca7d391ac2e1a472cc6c204a06/src/epub/images/titlepage.svg

Cover is missing the `:`. It looks better without it, but I guess we should probably be consistent. @acabal?

**Comment by acabal** [comment]
"His Parables and Poems" is a subtitle so it should not be in the cover, titlepage, or SE identifier. Subtitles appear in the metadata and in the halftitle if there is one.

**Comment by samisiddiqui** [comment]
Resolved as of https://github.com/samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems/commit/b37a1941e63719a122c8e846b3575bfe2a1a92d5
