### ISSUE TITLE
Introduction has the wrong epub:type

### ISSUE THREAD

**Issue by robinwhittleton** [samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems#6]
The intro file has `epub:type="volume se:short-story"`. I think a better choice would be `epub:type="prologue"` (“An introductory section that sets the background to a story, typically part of the narrative.” according to Z39.98-2012 Structural Semantics Vocabulary). If this change is made then it would be good to rename the file to prologue.xhtml, update the manifest and spine, change the `<body>`’s `bodymatter` to `frontmatter`, and give it an `epub:type="frontmatter prologue"` in the ToC landmarks. For an example, see the [prologue](https://github.com/standardebooks/mark-twain_a-connecticut-yankee-in-king-arthurs-court/blob/master/src/epub/text/prologue.xhtml) and [ToC](https://github.com/standardebooks/mark-twain_a-connecticut-yankee-in-king-arthurs-court/blob/master/src/epub/toc.xhtml) in A Connecticut Yankee in King Arthur’s Court.

It’s also missing a heading, but I think that’s OK as the original source doesn’t have one either.

**Comment by samisiddiqui** [comment]
Resolved as of https://github.com/samisiddiqui/khalil-gibran_the-madman-his-parables-and-poems/commit/107cd87880528668553f8fdad1cc138fc64759f5
